print("Hello world")
print("What is ur name")
myname=input()
print("Its good to meet you,"+ myname)
print("The length of ur name is:")
print(len(myname))
print("What is ur age?")
myage=input()
print("you will be " + str(int(myage)+ 1 )+" in a year")